version: '3'
services:
  retro:
    build:
      context: .
      dockerfile: Dockerfile
      # target: production
    ports:
      - 80:80
      - 1337:1337
      - 39175:39175
      - 51413:51413
    volumes:
      - ./games:/var/lib/transmission-daemon/games:rw